# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the terraform-orb
  terraform: ovotech/terraform@1.6.5

jobs:
  terraform_plan:
    executor: terraform/terraform-0_12
    steps:
      - checkout
      - terraform/plan:
          path: infrastructure

  terraform_apply:
    executor: terraform/terraform-0_12
    steps:
      - checkout
      - terraform/apply:
          path: infrastructure

workflows:
  commit:
    jobs:
      - terraform_plan:
          filters:
            branches:
              ignore:
                master
      - terraform_apply:
          filters:
            branches:
              only:
                master
