# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
reference:
base_image: &base_image hashicorp/terraform:light
working_directory: &working_directory ~/project

orbs:
  aws-cli: circleci/aws-cli@1.0.0

default_config: &default_config
  executor: aws-cli/default
  working_directory: *working_directory
  docker:
    - image: *base_image
  environment:
    BASH_ENV: /root/.bashrc
    TERRAFORM_ENV: /root/project/infrastructure

repo_cache_key: &repo_cache_key v2-repo-{{ .Branch }}-{{ .Revision }}

# Restore repo from cache
restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

set_terraform_environment: &set_terraform_environment
  run:
    name: set terraform environment
    command: |
      cd && touch $BASH_ENV

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      source $BASH_ENV
      cd $TERRAFORM_ENV
      terraform init

apply_job: &apply_job
  <<: *default_config
  steps:
    - *restore_repo
    - *set_terraform_environment
    - *terraform_init
    - attach_workspace:
        at: *working_directory
    - run:
        name: terraform apply
        command: |
          source $BASH_ENV
          cd $TERRAFORM_ENV
          terraform apply
    - *save_repo

jobs:
  build:
    <<: *default_config
    steps:
      - checkout
      - aws-cli/setup
      - *set_terraform_environment
      - *terraform_init
      - run:
          name: terraform fmt
          command: |
            source $BASH_ENV
            cd $TERRAFORM_ENV
            terraform fmt
      - *save_repo

  plan:
    <<: *default_config
    steps:
      - *restore_repo
      - *set_terraform_environment
      - *terraform_init
      - run:
          name: terraform plan
          command: |
            source $BASH_ENV
            cd $TERRAFORM_ENV
            terraform plan

  apply:
    <<: *apply_job
  apply-with-approval:
    <<: *apply_job

  destroy:
    <<: *default_config
    steps:
      - *restore_repo
      - *set_terraform_environment
      - *terraform_init
      - run:
          name: destroy environment
          command: |
            source $BASH_ENV
            cd $TERRAFORM_ENV
            terraform destroy --auto-approve

workflows:
  version: 2
  build_plan_approve_apply:
    jobs:
      - build
      - plan:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold
